from __future__ import annotations

import hashlib
import re
from typing import Iterable

from config import CATEGORY_ICONS
from dataset import Fact


# These are intentionally ordinary Unicode emoji, not Telegram custom emoji.
# They work as plain text and therefore do not depend on Telegram Premium or
# custom-emoji entity eligibility.
CONTEXT_LABELS = (
    "💡 WHY IT'S INTERESTING",
    "🔎 THE INTERESTING PART",
    "✨ ONE MORE THING",
    "📖 A LITTLE MORE CONTEXT",
    "🌍 THE BIGGER PICTURE",
    "🧩 HERE'S THE CATCH",
)

# Match more specific entities before broader concepts. A compact keyword engine
# keeps output deterministic, fast, and independent of an AI/API call.
SUBJECT_RULES: tuple[tuple[tuple[str, ...], str, int], ...] = (
    # Animals
    (("octopus",), "🐙", 100),
    (("octopuses", "octopi"), "🐙", 100),
    (("shark",), "🦈", 100),
    (("whale",), "🐋", 100),
    (("dolphin",), "🐬", 100),
    (("elephant",), "🐘", 100),
    (("penguin",), "🐧", 100),
    (("bee",), "🐝", 95),
    (("butterfly",), "🦋", 95),
    (("spider",), "🕷️", 95),
    (("snake",), "🐍", 95),
    (("crocodile",), "🐊", 95),
    (("frog",), "🐸", 95),
    (("dinosaur",), "🦖", 100),
    (("bat",), "🦇", 95),
    (("bird",), "🐦", 80),
    (("fish",), "🐟", 80),
    (("cat",), "🐈", 80),
    (("dog",), "🐕", 80),
    (("horse",), "🐎", 90),
    (("cow",), "🐄", 90),
    # Space
    (("black hole",), "🕳️", 100),
    (("astronaut",), "🧑‍🚀", 100),
    (("telescope",), "🔭", 95),
    (("saturn",), "🪐", 100),
    (("jupiter",), "🪐", 100),
    (("uranus",), "🪐", 100),
    (("neptune",), "🪐", 100),
    (("mars",), "🔴", 100),
    (("moon",), "🌙", 100),
    (("moons",), "🌙", 100),
    (("lunar",), "🌙", 95),
    (("sun",), "☀️", 100),
    (("solar",), "☀️", 95),
    (("planet",), "🪐", 85),
    (("planets",), "🪐", 85),
    (("galaxy",), "🌌", 95),
    (("star",), "⭐", 90),
    (("comet",), "☄️", 100),
    (("asteroid",), "☄️", 95),
    # Human body / psychology
    (("brain",), "🧠", 100),
    (("heart",), "❤️", 100),
    (("blood",), "🩸", 100),
    (("bone",), "🦴", 100),
    (("eye",), "👁️", 95),
    (("dna",), "🧬", 100),
    (("gene",), "🧬", 95),
    (("memory",), "🧠", 95),
    (("sleep",), "😴", 95),
    (("dream",), "💭", 90),
    (("emotion",), "💭", 90),
    # Science / nature
    (("volcano",), "🌋", 100),
    (("earthquake",), "🌎", 100),
    (("storm",), "🌪️", 95),
    (("hurricane",), "🌀", 100),
    (("tornado",), "🌪️", 100),
    (("lightning",), "⚡", 100),
    (("thunder",), "⛈️", 95),
    (("rainbow",), "🌈", 100),
    (("forest",), "🌲", 95),
    (("tree",), "🌳", 90),
    (("flower",), "🌸", 90),
    (("coral",), "🪸", 100),
    (("iceberg",), "🧊", 100),
    (("desert",), "🏜️", 95),
    (("mountain",), "⛰️", 95),
    (("river",), "🏞️", 90),
    (("waterfall",), "💧", 95),
    (("temperature",), "🌡️", 100),
    (("atom",), "⚛️", 100),
    (("molecule",), "🧪", 90),
    (("chemistry",), "🧪", 90),
    (("laboratory",), "🧪", 95),
    (("microscope",), "🔬", 100),
    (("virus",), "🦠", 100),
    (("bacteria",), "🦠", 100),
    # History / civilizations / mythology
    (("ancient egypt",), "🏺", 100),
    (("egyptian",), "🏺", 95),
    (("pyramid",), "🔺", 100),
    (("maya",), "🏺", 100),
    (("ruler",), "👑", 100),
    (("king",), "👑", 95),
    (("queen",), "👑", 95),
    (("palace",), "🏛️", 95),
    (("ceremony",), "🎭", 90),
    (("vessel",), "🏺", 95),
    (("aztec",), "🏺", 100),
    (("roman",), "🏛️", 95),
    (("rome",), "🏛️", 100),
    (("greek",), "🏛️", 95),
    (("greece",), "🏛️", 100),
    (("viking",), "🛡️", 100),
    (("samurai",), "⚔️", 100),
    (("battle",), "⚔️", 95),
    (("war",), "⚔️", 90),
    (("archaeology",), "🏺", 100),
    (("mythology",), "📜", 95),
    (("myth",), "📜", 90),
    # Technology / inventions
    (("smartphone",), "📱", 100),
    (("mobile phone",), "📱", 100),
    (("computer",), "💻", 100),
    (("internet",), "🌐", 100),
    (("robot",), "🤖", 100),
    (("artificial intelligence",), "🤖", 100),
    (("ai",), "🤖", 95),
    (("electricity",), "⚡", 100),
    (("engine",), "⚙️", 95),
    (("machine",), "⚙️", 85),
    (("invention",), "💡", 90),
    (("light bulb",), "💡", 100),
    (("printing press",), "📰", 100),
    (("camera",), "📷", 95),
    (("telephone",), "☎️", 95),
    # Food
    (("coffee",), "☕", 100),
    (("chocolate",), "🍫", 100),
    (("pizza",), "🍕", 100),
    (("bread",), "🍞", 95),
    (("sugar",), "🍬", 95),
    (("spice",), "🌶️", 95),
    (("pepper",), "🌶️", 90),
    (("apple",), "🍎", 90),
    (("banana",), "🍌", 90),
    (("honey",), "🍯", 100),
    (("cheese",), "🧀", 95),
    (("tea",), "🍵", 95),
    # Money / economics
    (("bitcoin",), "₿", 100),
    (("cryptocurrency",), "🪙", 100),
    (("money",), "💰", 95),
    (("coin",), "🪙", 100),
    (("bank",), "🏦", 95),
    (("gold",), "🥇", 95),
    (("stock market",), "📈", 100),
    (("inflation",), "📈", 90),
    # Language / everyday life
    (("language",), "🔤", 90),
    (("alphabet",), "🔤", 100),
    (("writing",), "✍️", 100),
    (("book",), "📖", 90),
    (("sleeping",), "😴", 95),
    (("home",), "🏠", 85),
    (("house",), "🏠", 85),
    # Records / extremes / mystery
    (("world record",), "🏆", 100),
    (("record",), "🏆", 85),
    (("largest",), "📏", 90),
    (("smallest",), "📏", 90),
    (("highest",), "📏", 90),
    (("lowest",), "📏", 90),
    (("longest",), "📏", 90),
    (("shortest",), "📏", 90),
    (("deepest",), "⬇️", 90),
    (("fastest",), "⚡", 90),
    (("mystery",), "🕵️", 100),
    (("unexplained",), "🧩", 100),
)

# Explicit country names used only for Country Facts entries.
COUNTRY_FLAGS = {
    'saint helena, ascension and tristan da cunha': 'SH',
    'south georgia and the south sandwich islands': 'GS',
    "korea, democratic people's republic of": 'KP',
    'congo, the democratic republic of the': 'CD',
    "democratic people's republic of korea": 'KP',
    'united states minor outlying islands': 'UM',
    'heard island and mcdonald islands': 'HM',
    'venezuela, bolivarian republic of': 'VE',
    'bonaire, sint eustatius and saba': 'BQ',
    "lao people's democratic republic": 'LA',
    'saint vincent and the grenadines': 'VC',
    'bolivia, plurinational state of': 'BO',
    'micronesia, federated states of': 'FM',
    'british indian ocean territory': 'IO',
    'holy see (vatican city state)': 'VA',
    'tanzania, united republic of': 'TZ',
    'falkland islands (malvinas)': 'FK',
    'french southern territories': 'TF',
    'saint martin (french part)': 'MF',
    'iran, islamic republic of': 'IR',
    'saint pierre and miquelon': 'PM',
    'sint maarten (dutch part)': 'SX',
    'taiwan, province of china': 'TW',
    'central african republic': 'CF',
    'northern mariana islands': 'MP',
    'turks and caicos islands': 'TC',
    'united states of america': 'US',
    'cocos (keeling) islands': 'CC',
    'virgin islands, british': 'VG',
    'bosnia and herzegovina': 'BA',
    'svalbard and jan mayen': 'SJ',
    'saint kitts and nevis': 'KN',
    'sao tome and principe': 'ST',
    'moldova, republic of': 'MD',
    'syrian arab republic': 'SY',
    'united arab emirates': 'AE',
    'virgin islands, u.s.': 'VI',
    'antigua and barbuda': 'AG',
    'palestine, state of': 'PS',
    'trinidad and tobago': 'TT',
    'dominican republic': 'DO',
    'korea, republic of': 'KR',
    'russian federation': 'RU',
    'state of palestine': 'PS',
    'brunei darussalam': 'BN',
    'equatorial guinea': 'GQ',
    'republic of korea': 'KR',
    'wallis and futuna': 'WF',
    'christmas island': 'CX',
    'french polynesia': 'PF',
    'marshall islands': 'MH',
    'papua new guinea': 'PG',
    'saint barthélemy': 'BL',
    'north macedonia': 'MK',
    'solomon islands': 'SB',
    'american samoa': 'AS',
    'cayman islands': 'KY',
    'czech republic': 'CZ',
    'norfolk island': 'NF',
    'united kingdom': 'GB',
    'western sahara': 'EH',
    'bouvet island': 'BV',
    'cote d ivoire': 'CI',
    "côte d'ivoire": 'CI',
    'côte d’ivoire': 'CI',
    'faroe islands': 'FO',
    'french guiana': 'GF',
    'great britain': 'GB',
    'guinea-bissau': 'GW',
    'liechtenstein': 'LI',
    'new caledonia': 'NC',
    'united states': 'US',
    'åland islands': 'AX',
    'burkina faso': 'BF',
    'cook islands': 'CK',
    'saudi arabia': 'SA',
    'sierra leone': 'SL',
    'south africa': 'ZA',
    'turkmenistan': 'TM',
    'vatican city': 'VA',
    'afghanistan': 'AF',
    'el salvador': 'SV',
    'isle of man': 'IM',
    'ivory coast': 'CI',
    'netherlands': 'NL',
    'new zealand': 'NZ',
    'north korea': 'KP',
    'philippines': 'PH',
    'puerto rico': 'PR',
    'saint lucia': 'LC',
    'south korea': 'KR',
    'south sudan': 'SS',
    'switzerland': 'CH',
    'timor-leste': 'TL',
    'antarctica': 'AQ',
    'azerbaijan': 'AZ',
    'bangladesh': 'BD',
    'cabo verde': 'CV',
    'cape verde': 'CV',
    'costa rica': 'CR',
    'guadeloupe': 'GP',
    'kazakhstan': 'KZ',
    'kyrgyzstan': 'KG',
    'luxembourg': 'LU',
    'madagascar': 'MG',
    'martinique': 'MQ',
    'mauritania': 'MR',
    'montenegro': 'ME',
    'montserrat': 'MS',
    'mozambique': 'MZ',
    'san marino': 'SM',
    'seychelles': 'SC',
    'tajikistan': 'TJ',
    'uzbekistan': 'UZ',
    'argentina': 'AR',
    'australia': 'AU',
    'gibraltar': 'GI',
    'greenland': 'GL',
    'guatemala': 'GT',
    'hong kong': 'HK',
    'indonesia': 'ID',
    'lithuania': 'LT',
    'mauritius': 'MU',
    'nicaragua': 'NI',
    'palestine': 'PS',
    'singapore': 'SG',
    'sri lanka': 'LK',
    'venezuela': 'VE',
    'anguilla': 'AI',
    'barbados': 'BB',
    'botswana': 'BW',
    'bulgaria': 'BG',
    'cambodia': 'KH',
    'cameroon': 'CM',
    'colombia': 'CO',
    'djibouti': 'DJ',
    'dominica': 'DM',
    'eswatini': 'SZ',
    'ethiopia': 'ET',
    'guernsey': 'GG',
    'holy see': 'VA',
    'honduras': 'HN',
    'kiribati': 'KI',
    'malaysia': 'MY',
    'maldives': 'MV',
    'mongolia': 'MN',
    'pakistan': 'PK',
    'paraguay': 'PY',
    'pitcairn': 'PN',
    'portugal': 'PT',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'suriname': 'SR',
    'tanzania': 'TZ',
    'thailand': 'TH',
    'viet nam': 'VN',
    'zimbabwe': 'ZW',
    'albania': 'AL',
    'algeria': 'DZ',
    'andorra': 'AD',
    'armenia': 'AM',
    'austria': 'AT',
    'bahamas': 'BS',
    'bahrain': 'BH',
    'belarus': 'BY',
    'belgium': 'BE',
    'bermuda': 'BM',
    'bolivia': 'BO',
    'burundi': 'BI',
    'comoros': 'KM',
    'croatia': 'HR',
    'curaçao': 'CW',
    'czechia': 'CZ',
    'denmark': 'DK',
    'ecuador': 'EC',
    'eritrea': 'ER',
    'estonia': 'EE',
    'finland': 'FI',
    'georgia': 'GE',
    'germany': 'DE',
    'grenada': 'GD',
    'hungary': 'HU',
    'iceland': 'IS',
    'ireland': 'IE',
    'jamaica': 'JM',
    'lebanon': 'LB',
    'lesotho': 'LS',
    'liberia': 'LR',
    'mayotte': 'YT',
    'moldova': 'MD',
    'morocco': 'MA',
    'myanmar': 'MM',
    'namibia': 'NA',
    'nigeria': 'NG',
    'romania': 'RO',
    'réunion': 'RE',
    'senegal': 'SN',
    'somalia': 'SO',
    'tokelau': 'TK',
    'tunisia': 'TN',
    'türkiye': 'TR',
    'ukraine': 'UA',
    'uruguay': 'UY',
    'vanuatu': 'VU',
    'vietnam': 'VN',
    'angola': 'AO',
    'belize': 'BZ',
    'bhutan': 'BT',
    'brazil': 'BR',
    'brunei': 'BN',
    'canada': 'CA',
    'cyprus': 'CY',
    'france': 'FR',
    'gambia': 'GM',
    'greece': 'GR',
    'guinea': 'GN',
    'guyana': 'GY',
    'israel': 'IL',
    'jersey': 'JE',
    'jordan': 'JO',
    'kuwait': 'KW',
    'latvia': 'LV',
    'malawi': 'MW',
    'mexico': 'MX',
    'monaco': 'MC',
    'norway': 'NO',
    'panama': 'PA',
    'poland': 'PL',
    'russia': 'RU',
    'rwanda': 'RW',
    'serbia': 'RS',
    'sweden': 'SE',
    'turkey': 'TR',
    'tuvalu': 'TV',
    'u.a.e.': 'AE',
    'u.s.a.': 'US',
    'uganda': 'UG',
    'zambia': 'ZM',
    'aruba': 'AW',
    'benin': 'BJ',
    'burma': 'MM',
    'chile': 'CL',
    'china': 'CN',
    'congo': 'CG',
    'egypt': 'EG',
    'gabon': 'GA',
    'ghana': 'GH',
    'haiti': 'HT',
    'india': 'IN',
    'italy': 'IT',
    'japan': 'JP',
    'kenya': 'KE',
    'libya': 'LY',
    'macao': 'MO',
    'malta': 'MT',
    'nauru': 'NR',
    'nepal': 'NP',
    'niger': 'NE',
    'palau': 'PW',
    'qatar': 'QA',
    'samoa': 'WS',
    'spain': 'ES',
    'sudan': 'SD',
    'syria': 'SY',
    'tonga': 'TO',
    'yemen': 'YE',
    'chad': 'TD',
    'cuba': 'CU',
    'fiji': 'FJ',
    'guam': 'GU',
    'iran': 'IR',
    'iraq': 'IQ',
    'laos': 'LA',
    'mali': 'ML',
    'niue': 'NU',
    'oman': 'OM',
    'peru': 'PE',
    'togo': 'TG',
    'u.s.': 'US',
    'uae': 'AE',
    'usa': 'US',
    'uk': 'GB',
}

FALLBACK_BY_CATEGORY = {
    "Science": "⚛️",
    "Space": "🔭",
    "Human Body": "🧬",
    "Psychology": "💭",
    "Animals": "🐾",
    "Geography": "🗺️",
    "History": "📜",
    "Technology": "⚙️",
    "Mystery & Unexplained": "🧩",
    "Ancient Civilizations": "🏺",
    "World Records & Extremes": "🏆",
    "Nature": "🌱",
    "Food": "🍴",
    "Inventions": "💡",
    "Country Facts": "🌐",
    "Mythology & Legends": "📜",
    "Ocean & Marine": "🐚",
    "Language": "💬",
    "Money & Economics": "💵",
    "Everyday Life": "🏠",
}


def _normalize(text: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9]+", " ", text.lower())).strip()


def _stable_pick(key: str, values: Iterable[str]) -> str:
    choices = tuple(values)
    digest = hashlib.sha256(key.encode("utf-8")).digest()
    return choices[int.from_bytes(digest[:4], "big") % len(choices)]


def category_line(f: Fact) -> str:
    icon = CATEGORY_ICONS.get(f.category, "📚")
    return f"{icon} {f.category.upper()}"


def _country_flag(code: str) -> str:
    code = code.upper()
    if len(code) != 2 or not code.isalpha():
        return ""
    return "".join(chr(0x1F1E6 + ord(char) - ord("A")) for char in code)


def _country_subject(text: str, category: str) -> list[tuple[int, int, str]]:
    if category != "Country Facts":
        return []
    matches: list[tuple[int, int, str]] = []
    for index, (country, code) in enumerate(COUNTRY_FLAGS.items()):
        if re.search(rf"(?<![a-z0-9]){re.escape(country)}(?![a-z0-9])", text):
            matches.append((125 + min(20, len(country.split()) * 5), -index, _country_flag(code)))
            break
    return matches


def subject_emojis(f: Fact, *, max_items: int = 2) -> list[str]:
    text = _normalize(" ".join((f.title, f.fact, f.subcategory, f.category)))
    scored: list[tuple[int, int, str]] = _country_subject(text, f.category)

    for index, (phrases, emoji, base_score) in enumerate(SUBJECT_RULES):
        matched = False
        score = 0
        for phrase in phrases:
            normalized_phrase = _normalize(phrase)
            if not normalized_phrase:
                continue
            if re.search(rf"(?<![a-z0-9]){re.escape(normalized_phrase)}(?![a-z0-9])", text):
                matched = True
                # Longer phrase/entity matches outrank generic single-word matches.
                score = max(score, base_score + min(20, len(normalized_phrase.split()) * 5))
        if matched:
            scored.append((score, -index, emoji))

    selected: list[str] = []
    category_icon = CATEGORY_ICONS.get(f.category, "")
    for _, _, emoji in sorted(scored, reverse=True):
        if emoji == category_icon or emoji in selected:
            continue
        selected.append(emoji)
        if len(selected) >= max_items:
            break

    if selected:
        return selected

    fallback = FALLBACK_BY_CATEGORY.get(f.category, "📌")
    if fallback != category_icon:
        return [fallback]
    return ["📌"]


def context_label(f: Fact) -> str:
    # Stable per fact ID so the same post always renders identically on retries.
    return _stable_pick(f.fact_id or f.title or f.fact, CONTEXT_LABELS)
